name: Jobs secuenciales

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build"

  test:
    runs-on: ubuntu-latest
    needs: build  #  DEPENDENCIA
    steps:
      - run: echo "Test"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo "Deploy"
