name: Solo si cambia app

on:
  push:
    branches:
      - prueba
      - main
    paths:
      - 'app.txt'

jobs:
  verificar-cambio:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Mostrar mensaje
        run: echo "Se ha modificado app.txt, ejecutando workflow"

      - name: Mostrar contenido del archivo
        run: cat app.txt
